services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    volumes:
      - ./src:/app/src
      - ./resources:/app/resources
    depends_on:
      - grobid
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ALLOWED_USERS=${ALLOWED_USERS}
    mem_limit: 1g
    restart: always

  grobid:
    image: lfoppiano/grobid:latest-develop
    container_name: grobid
    ports:
      - "8070:8070"
    mem_limit: 6g
    restart: always
